name: Hermes Scraper (5min, 06:00–24:00 Asia/Taipei)

on:
  # GitHub Actions uses UTC. The two cron ranges below map to 06:00–23:59 Asia/Taipei (UTC+8).
  schedule:
    - cron: "*/5 22-23 * * *"  # 06:00–07:59 Asia/Taipei (前一天 22:00–23:59 UTC)
    - cron: "*/5 0-15 * * *"   # 08:00–23:59 Asia/Taipei (當天 00:00–15:59 UTC)
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: hermes-scraper-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      TZ: Asia/Taipei
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install Python deps
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Run scraper once
        env:
          LINE_CHANNEL_ACCESS_TOKEN: ${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}
          GMAIL_USER:                ${{ secrets.GMAIL_USER }}
          GMAIL_APP_PASSWORD:        ${{ secrets.GMAIL_APP_PASSWORD }}
